export {
  COMPANY_LOGO_STORAGE_KEY,
  COMPANY_ICON_STORAGE_KEY,
  COMPANY_CAROUSEL_IMAGE_1_STORAGE_KEY,
  COMPANY_CAROUSEL_IMAGE_2_STORAGE_KEY,
  COMPANY_CAROUSEL_IMAGE_3_STORAGE_KEY,
  COMPANY_OPERATIONAL_SETTINGS_STORAGE_KEY,
} from "@/services/company"